generator:
  class: sfPropelGenerator
  param:
    model_class:           Guide
    theme:                 mfAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              Guide
    plural:                Guides
    route_prefix:          guide
    with_propel_route:     1
    actions_base_class:    sfActions
    i18n_catalogue:        guide

    config:
      actions: ~
      fields:
        company_id:        { label: Empresa }
        name:              { label: Nome }
        observations:      { label: Observações }
      list:
        title:             A listar Guias/Biólogos
        display:           [company, name]
        peer_method:       doSelectByCompany
      filter:
        class: false
      form:    ~
      edit:
        title:             A editar %%name%%
      new:
        title:             Novo Guia/Biólogo
